config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root 'posts#index'

  get :create, to: 'posts#new'
  post :create, to: 'posts#create'

  get :destroy, to: 'posts#destroy'

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    has_and_belongs_to_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = if params[:category]
            Post.joins(:categories).where(categories:{id:params[:category]})
        else
            Post.all
        end
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        if @post.save
            redirect_to root_path
        else
            render 'new'
        end
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
        @post.assign_attributes(post_params)
        if @post.save
            redirect_to root_path
        else
            render 'new'
        end
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to root_path
    end

    private
        def post_params
            params.require(:post).permit(:title, :description)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="https://getbootstrap.com/docs/3.3/favicon.ico">

    <title>Blog </title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/3.3/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="https://getbootstrap.com/docs/3.3/assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/3.3/examples/blog/blog.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="https://getbootstrap.com/docs/3.3/assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="https://getbootstrap.com/docs/3.3/assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item active" href="#">Home</a>
          <% Category.all.each do |category|%>
          <%= link_to category.name, posts_path(category: category.id), class:"blog-nav-item" %>
          <% end %>
          <br />
          <a  class="blog-nav-item active" href="/posts/new" >Create a post</a>
        </nav>
      </div>
    </div>

    <div class="container">

      <%= yield %>

    </div><!-- /.container -->

    <footer class="blog-footer">
      <p>Blog template built for <a href="http://getbootstrap.com">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/3.3/assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://getbootstrap.com/docs/3.3/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="https://getbootstrap.com/docs/3.3/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>edit a post</h1>
<%= form_for( @post, url: posts_path(@post)) do |f| %>
    Title:
    <%= f.text_field :title, placeholder: "Title" %>
    <br />
    Description:
    <%= f.text_area :description, placeholder: "Description" %>
    <br />
    <%= f.submit "Update" %>
<% end %>

app/views/posts/index.html.erb
      <div class="row">

        <div class="col-sm-8 blog-main">
        <% @posts.each do |post|%>

          <div class="blog-post">
            <h2 class="blog-post-title"><%= post.title %></h2>
            <p class="blog-post-meta"><%= l post.updated_at %> </p>
            <% post.categories.each do |category|%>
                <span class="label label-default"><%= category.name%></span>
            <% end %>

            <%= post.description %>
          </div><!-- /.blog-post -->
        

          <nav>
            <ul class="pager">
              <li> <%= link_to "Edit", edit_post_path(post)%></li>
              <li> <%= link_to "Delete", post_path(post), method: :delete %></li>
            </ul>
          </nav>
          <% end %>

        </div><!-- /.blog-main -->

       

      </div><!-- /.row -->

app/views/posts/new.html.erb
<h1>create a post</h1>
<%= form_for( @post, url: posts_path) do |f| %>
    Title:
    <%= f.text_field :title, placeholder: "Title" %>
    <br />
    Description:
    <%= f.text_area :description, placeholder: "Description" %>
    <br />
    <%= f.submit "Create" %>
<% end %>